spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud?useSLL=false&serverTimeZone=UTC&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${spring.application.name}
      #mongodb+srv://james:James123.@crud.brv17.mongodb.net/monolito?retryWrites=true&w=majority&maxIdleTimeMS=15000&ssl=true
      database: monolito